/**
 * The catalog PDF is generated by a background job, so the operator who asked
 * for it has nothing to watch: `usePollWhileActive` re-renders the list every
 * five seconds and the card silently changes status at some point. This
 * provider is the one client component that sees every poll result, so it is
 * where "your catalog is ready" has to come from.
 *
 * Two things this file exists to pin, both of which a naive
 * "render a toast for whatever status is on screen" passes on the happy path
 * and fails in production:
 *
 * 1. **Once per catalog, not once per tick.** The poll keeps re-rendering
 *    while any OTHER catalog is still generating, so reacting to the current
 *    status announces the same finished catalog every five seconds forever.
 * 2. **Nothing is announced for a catalog that was already finished at
 *    load.** The operator did not just do anything; a card that finished
 *    yesterday is not news, and the page opens with a stack of them.
 *
 * A poll tick is simulated by re-rendering with FRESH objects, which is what
 * `router.refresh()` actually produces: the server component re-runs, re-reads
 * the table and hands down a new array of new rows.
 *
 * See `.claude/skills/component-testing/SKILL.md` for why this is `.test.tsx`.
 */
import { render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";

import type { Catalog } from "@/shared/db/schema";
import { ToastProvider } from "@/shared/ui/ToastProvider";
import { CatalogPollProvider } from "./CatalogPollProvider";

vi.mock("next/navigation", () => ({ useRouter: () => ({ refresh: vi.fn() }) }));

/** A row as `listCatalogsForUser` returns it — every column, none of them optional. */
function catalog(
  id: string,
  title: string,
  uploadStatus: Catalog["uploadStatus"],
): Catalog {
  return {
    id,
    userId: "u1",
    title,
    categories: [{ categoryL1: "Frenos", categoryL2: null }],
    productsPerPage: 12,
    uploadStatus,
    r2Key: uploadStatus === "uploaded" ? `catalogs/${id}.pdf` : null,
    r2Url: uploadStatus === "uploaded" ? `https://r2.example/${id}.pdf` : null,
    createdAt: new Date("2026-09-01T10:00:00Z"),
  };
}

function renderPoll(catalogs: Catalog[]) {
  const { rerender } = render(
    <ToastProvider>
      <CatalogPollProvider initialCatalogs={catalogs}>
        <p>Mis catálogos</p>
      </CatalogPollProvider>
    </ToastProvider>,
  );

  /** One poll tick: same data, new objects, exactly as a server re-render hands it down. */
  return function tick(next: Catalog[]) {
    rerender(
      <ToastProvider>
        <CatalogPollProvider initialCatalogs={next.map((c) => ({ ...c }))}>
          <p>Mis catálogos</p>
        </CatalogPollProvider>
      </ToastProvider>,
    );
  };
}

const READY = "El catálogo «Frenos y suspensión» está listo";
const FAILED = "No se pudo generar el catálogo «Frenos y suspensión»";

describe("CatalogPollProvider — the generation finishes while nobody is watching", () => {
  it("announces a catalog that finishes while the page is open", async () => {
    const tick = renderPoll([catalog("c1", "Frenos y suspensión", "pending")]);

    tick([catalog("c1", "Frenos y suspensión", "uploading")]);
    tick([catalog("c1", "Frenos y suspensión", "uploaded")]);

    expect(await screen.findByText(READY)).toBeInTheDocument();
  });

  it("says the generation failed, rather than leaving the card to be read", async () => {
    const tick = renderPoll([catalog("c1", "Frenos y suspensión", "pending")]);

    tick([catalog("c1", "Frenos y suspensión", "failed")]);

    expect(await screen.findByText(FAILED)).toBeInTheDocument();
    expect(screen.queryByText(READY)).not.toBeInTheDocument();
  });

  /**
   * THE defect this design is against. The poll keeps ticking while `c2` is
   * still generating, and every one of those ticks re-renders `c1` sitting at
   * `uploaded`. A component that reacts to the STATUS rather than to the
   * TRANSITION into it announces the same finished catalog every five seconds
   * until the operator leaves the page.
   */
  it("announces a finished catalog once, not on every poll tick that follows", async () => {
    const pending = catalog("c2", "Otro catálogo", "pending");
    const tick = renderPoll([catalog("c1", "Frenos y suspensión", "uploading"), pending]);

    tick([catalog("c1", "Frenos y suspensión", "uploaded"), pending]);
    await screen.findByText(READY);

    // Four more ticks over data that has not changed — the second catalog is
    // still generating, so the poll is still running.
    for (let i = 0; i < 4; i++) {
      tick([catalog("c1", "Frenos y suspensión", "uploaded"), pending]);
    }

    expect(screen.getAllByText(READY)).toHaveLength(1);
  });

  /**
   * The page opens on every catalog this user has ever generated, and all but
   * the newest finished days ago. Announcing them is not a confirmation, it is
   * a stack of toasts over a screen the operator just navigated to.
   */
  it("says nothing about catalogs that were already finished when the page loaded", async () => {
    const tick = renderPoll([
      catalog("c1", "Frenos y suspensión", "uploaded"),
      catalog("c2", "Otro catálogo", "failed"),
      catalog("c3", "Tercero", "pending"),
    ]);

    tick([
      catalog("c1", "Frenos y suspensión", "uploaded"),
      catalog("c2", "Otro catálogo", "failed"),
      catalog("c3", "Tercero", "pending"),
    ]);

    // A positive anchor first: the subtree really did render, so these two
    // negatives are about the toasts and not about an empty document.
    expect(screen.getByText("Mis catálogos")).toBeInTheDocument();
    expect(screen.queryByText(READY)).not.toBeInTheDocument();
    expect(screen.queryByText("No se pudo generar el catálogo «Otro catálogo»")).not.toBeInTheDocument();
  });

  /**
   * The same rule one step later: a catalog this mount has never seen arrives
   * already finished (generated in another tab, or by the admin listing that
   * shows every user's rows). It is not this operator's news either — only a
   * status this mount watched CHANGE is.
   */
  it("says nothing about a catalog that first appears already finished", async () => {
    const pending = catalog("c2", "Otro catálogo", "pending");
    const tick = renderPoll([pending]);

    tick([catalog("c1", "Frenos y suspensión", "uploaded"), pending]);

    expect(screen.queryByText(READY)).not.toBeInTheDocument();
  });
});
