"use client";

import { useEffect, useRef } from "react";

import type { Catalog } from "@/shared/db/schema";
import { usePollWhileActive } from "@/hooks/usePollWhileActive";
import { useToast } from "@/shared/ui/ToastProvider";

/**
 * The catalog PDF is generated by a background job, so there is nothing on
 * screen for the operator to wait on: `usePollWhileActive` re-renders this
 * list every five seconds and the card quietly changes status. This component
 * already sees every poll result, so the notice belongs here.
 *
 * It fires on the TRANSITION into a terminal status, never on the status
 * itself — `seen` holds the last `uploadStatus` this mount observed per
 * catalog, and a toast goes out only when that status actually moved. Two
 * things fall out of it, and both are the point:
 *
 * - The poll keeps ticking while any OTHER catalog generates, re-rendering the
 *   finished one every five seconds. Reacting to the status would announce it
 *   on every one of those ticks, forever.
 * - A catalog whose FIRST observation is already terminal is recorded and not
 *   announced. That covers the page opening on a stack of catalogs that
 *   finished days ago, and a row arriving already-finished from another tab —
 *   in neither case did the operator just do anything.
 *
 * No progress is reported because none exists: the statuses are
 * `pending -> uploading -> uploaded | failed` and the job publishes nothing in
 * between.
 */
export function CatalogPollProvider({
  initialCatalogs,
  children,
}: {
  initialCatalogs: Catalog[];
  children: React.ReactNode;
}) {
  usePollWhileActive(initialCatalogs);
  const { addToast } = useToast();
  const seen = useRef(new Map<string, string>());

  useEffect(() => {
    for (const { id, title, uploadStatus } of initialCatalogs) {
      const previous = seen.current.get(id);
      seen.current.set(id, uploadStatus);
      // Never observed before, or unchanged since: not news either way.
      if (previous === undefined || previous === uploadStatus) continue;

      if (uploadStatus === "uploaded") {
        addToast("success", `El catálogo «${title}» está listo`);
      } else if (uploadStatus === "failed") {
        addToast("error", `No se pudo generar el catálogo «${title}»`);
      }
    }
  }, [initialCatalogs, addToast]);

  return <>{children}</>;
}
