/**
 * customers/portal-token.ts — the customer-portal access token (WU2).
 *
 * The token is the only credential on the printed "Copia del cliente", so it is
 * 256 bits from the OS CSPRNG and takes no input: nothing about the customer
 * can leak into it. Server-only (`node:crypto`); never import from a
 * `"use client"` file.
 */
import { randomBytes } from "node:crypto";

import type { Cliente } from "@/shared/db/schema";

export function generatePortalToken(): string {
  return randomBytes(32).toString("base64url");
}

/**
 * The token a customer holds after a consent change. A grant keeps an existing
 * token (one is never regenerated by a repeat) and issues one otherwise; a
 * revoke ALWAYS yields null, so the next grant finds none and mints a new one:
 * a revoked token is never restored.
 */
export function tokenAfterConsent(
  granted: boolean,
  existing: string | null,
  generate: () => string = generatePortalToken,
): string | null {
  if (!granted) return null;
  return existing ?? generate();
}

export type PublicCliente = Omit<Cliente, "portalToken">;

/** The row as it may leave the server: every column except the portal token. */
export function toPublicCliente(row: Cliente): PublicCliente {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars -- dropping the field is the point
  const { portalToken, ...rest } = row;
  return rest;
}
